name: Deployment Pipeline

env:
  CONDITION: ${{ contains(github.event.head_commit.message, '#skip') }}

on:
  push:
    branches:
      - main
  pull_request:
    branches: [main]
    types: [opened, synchronize]

jobs:
  simple_deployment_pipeline:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
      - name: Install dependencies
        run: npm install
      - name: Check style
        run: npm run eslint
      - name: Build Source
        run: npm run build
      - name: Test
        run: npm run test
      - name: Install Playwright Browsers
        run: npx playwright install --with-deps
      - name: E2E Tests
        run: npm run test:e2e
      - name: Trigger Deployment
        if: github.event_name == 'push'
        run: curl https://api.render.com/deploy/srv-${{ secrets.RENDER_SERVICE_ID }}?key=${{ secrets.RENDER_API_KEY }}

  tag_release:
    needs: [simple_deployment_pipeline]
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4 
        with:
          fetch-depth: '0'

      - name: Bump version and push tag
        if: github.event_name == 'push' && env.CONDITION == false
        uses: anothrNick/github-tag-action@1.73.0 
        env:
          DEFAULT__BUMP: patch
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}